server:
  port: 8080

spring:
  Kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: order-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: INFO